name: sgvae-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.10.0
  - numpy
  - scikit-learn
  - pandas
  - matplotlib
  - nltk
  - rdkit
  - h5py
  - pip
  - pip:
      - skorch==0.11.0
      - torchinfo==1.6.3
      - tqdm
      - pyyaml
